#!/bin/sh

set -o errexit
set -o nounset


python manage.py makemigrations
python manage.py migrate
python manage.py loaddata users/fixtures/demo_users.json
python manage.py loaddata posts/fixtures/demo_posts.json
python manage.py runserver 0.0.0.0:8000
