#!/bin/sh

set -o errexit
set -o nounset


python manage.py makemigrations
python manage.py migrate
#python manage.py loaddata fixtures/demo_users.yaml
#python manage.py loaddata fixtures/demo_posts.yaml
python manage.py runserver 0.0.0.0:8000
